In [13]:
import numpy as np 
import pandas as pd 
from datetime import datetime

from sklearn.linear_model import LinearRegression

/home/rileydavid/.local/lib/python3.10/site-packages/pandas/core/series.py:28: RuntimeWarning: coroutine 'WebSocketClient._start_receiving' was never awaited
  from pandas._libs import (
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

In [15]:
files = ['XBTUSD_full.csv', 'XBTUSD_Q1.csv', 'XBTUSD_Q2.csv']
df = pd.DataFrame()
for file in files:
    data = pd.read_csv(file, names=["time", "price", "volume"], header=None)
    df = pd.concat([df, data], axis=0)
# df.to_csv('XBTUSD.csv', index=False, header=None)

df.tail()

               time    price    volume
3276196  1688169557  30475.0  0.000614
3276197  1688169568  30475.0  0.001608
3276198  1688169580  30475.0  0.076928
3276199  1688169587  30475.0  0.005634
3276200  1688169589  30475.0  0.000336

In [ ]:
# reduce size of dataframe
def split_dataframe(df, chunk_size = 5000000): 
    chunks = list()
    num_chunks = len(df) // chunk_size + 1
    for i in range(num_chunks):
        chunks.append(df[i*chunk_size:(i+1)*chunk_size])
    return chunks

df = split_dataframe(df)

In [18]:
# Training data
X = df.loc[:, ['time']]  # features
y = df.loc[:, 'price']  # target

print(X)

# Train the model
model = LinearRegression()
model.fit(X, y)

# the training data
#y_pred = pd.Series(model.predict(X), index=X.index)

               time
0        1381095255
1        1381179030
2        1381201115
3        1381201115
4        1381210004
...             ...
3276196  1688169557
3276197  1688169568
3276198  1688169580
3276199  1688169587
3276200  1688169589

[57792334 rows x 1 columns]

LinearRegression()

In [17]:
X.head()

                  time
0  2013-10-06 23:34:15
1  2013-10-07 22:50:30
2  2013-10-08 04:58:35
3  2013-10-08 04:58:35
4  2013-10-08 07:26:44

In [ ]:
d = {'time': [1695367381814, 1695367542643]}
df = pd.DataFrame(data=d)

df.head()

temp = model.predict(df)

temp[0]

In [1]:
import asyncio
import websockets
import time

class WebSocketClient:
    def __init__(self, host, port, secret):
        self._secret = secret
        self._host = host
        self._port = port

    def start(self):
        asyncio.get_event_loop().\
        run_until_complete(self._start_receiving())

    async def _start_receiving(self):
        url = f'ws://{self._host}:{self._port}/ws'
        try:
            async with websockets.connect(url) as websocket:
                await websocket.send("XBTUSD")
                while True:
                    time.sleep(0.8)
                    response = await websocket.recv()
                    print(f'Received Message: {response}')
        except websockets.ConnectionClosed as ex:
            print(ex)
            raise

if __name__ == "__main__":
    client = WebSocketClient("127.0.0.1", 8000, "secret")
    client.start()

RuntimeError: This event loop is already running

In [11]:
from dateutil import parser

print(parser.isoparse("2023-09-23T10:11:13.000773561+00:00").timestamp() * 1_000)

1695463873000.773